baseURL = 'https://samyukthakrishnar.github.io'
languageCode = 'en-us'
title = 'My Hugo Site'
theme = 'hyde'

[params]
    description = "This portfolio will take your attention across my field of interests and the projects that I have done as part of amFOSS praveshan   "
    themeColor = "black"  # You can change colors
    
[author]
    name = "Samyuktha Krishna R"

# Menu configuration

[menu]

[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
